version: '2.6'
services:
  node-exporter:
    image: bitnami/node-exporter:latest
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    restart: always
    networks:
      - GPN-stack
    ports:
      - 9100:9100
  
  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    restart: always
    networks:
      - GPN-stack
    ports:
      - 9090:9090
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    env_file:
      - ./config.env
    restart: always
    networks:
      - GPN-stack
    ports:
      - 3000:3000
    depends_on:
      - prometheus

networks:
  GPN-stack:
    name: GPN-stack
    driver: bridge

volumes:
  prometheus-data:
    name: prometheus-data
  grafana-data:
    name: grafana-data